from __future__ import annotations

import os
import struct
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
WORKSPACE_ROOT = PROJECT_ROOT / "workspace"


def ensure_session_dir(session_id: str) -> Path:
    session_dir = WORKSPACE_ROOT / session_id
    session_dir.mkdir(parents=True, exist_ok=True)
    return session_dir


def write_text(session_id: str, filename: str, content: str) -> Path:
    path = ensure_session_dir(session_id) / filename
    path.write_text(content, encoding="utf-8")
    return path


def write_bytes(session_id: str, filename: str, data: bytes) -> Path:
    path = ensure_session_dir(session_id) / filename
    path.write_bytes(data)
    return path


def artifact_url(session_id: str, filename: str) -> str:
    return f"/api/workspace/{session_id}/{filename}"


def artifact_meta(session_id: str, agent_id: str, filename: str, kind: str, title: str) -> dict:
    return {
        "agentId": agent_id,
        "filename": filename,
        "path": str(ensure_session_dir(session_id) / filename),
        "kind": kind,
        "title": title,
        "url": artifact_url(session_id, filename),
    }


def _write_var_len(value: int) -> bytes:
    buffer = []
    buffer.append(value & 0x7F)
    value >>= 7
    while value:
        buffer.append((value & 0x7F) | 0x80)
        value >>= 7
    return bytes(reversed(buffer))


def create_minimal_midi(session_id: str, filename: str = "track.mid") -> Path:
    """Create a tiny valid MIDI file (C major arpeggio)."""
    tempo = 500000
    track = bytearray()
    track.extend(_write_var_len(0))
    track.extend(b"\xFF\x51\x03")
    track.extend(struct.pack(">I", tempo)[1:])

    notes = [60, 64, 67, 72, 67, 64, 60, 62]
    for pitch in notes:
        track.extend(_write_var_len(0))
        track.extend(bytes([0x90, pitch, 0x60]))
        track.extend(_write_var_len(0x30))
        track.extend(bytes([0x80, pitch, 0x00]))

    track.extend(_write_var_len(0))
    track.extend(b"\xFF\x2F\x00")

    header = b"MThd" + struct.pack(">IHHH", 6, 0, 1, 480)
    track_chunk = b"MTrk" + struct.pack(">I", len(track)) + bytes(track)
    return write_bytes(session_id, filename, header + track_chunk)


def create_score_pdf(session_id: str, mission: str, filename: str = "score.pdf") -> Path:
    from fpdf import FPDF

    from .pdf_fonts import setup_pdf_fonts

    pdf = FPDF()
    pdf.add_page()
    body_font = setup_pdf_fonts(pdf)
    pdf.set_font(body_font, "B", 16)
    pdf.cell(190, 12, "Score Specialist - Sheet Preview", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font(body_font, "", 11)
    pdf.cell(190, 8, f"Mission: {mission[:80]}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.set_font("Courier", "", 10)
    for line in [
        "Treble staff preview",
        "Notes: C4 E4 G4 C5",
        "Key: C Major | Tempo: 82 BPM | Time: 4/4",
    ]:
        pdf.cell(190, 6, line, new_x="LMARGIN", new_y="NEXT")
    path = ensure_session_dir(session_id) / filename
    pdf.output(str(path))
    return path


def create_music_code(session_id: str, mission: str) -> Path:
    content = f'''"""Generated by Music Dev — {datetime.now(timezone.utc).isoformat()}"""
# Mission: {mission}

from music21 import stream, note, tempo, key

def generate(seed: int = 42) -> stream.Stream:
    s = stream.Stream()
    s.append(tempo.MetronomeMark(number=82))
    s.append(key.Key("C"))

    melody = ["C4", "E4", "G4", "A4", "G4", "E4", "C4", "D4"]
    for pitch in melody:
        s.append(note.Note(pitch, quarterLength=1.0))

    s.write("midi", fp="output/lofi_c_major.mid")
    return s

if __name__ == "__main__":
    generate()
'''
    return write_text(session_id, "music_generator.py", content)


def create_musicxml(session_id: str, mission: str) -> Path:
    content = f'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN"
  "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <work><work-title>{mission}</work-title></work>
  <part-list><score-part id="P1"><part-name>Melody</part-name></score-part></part-list>
  <part id="P1">
    <measure number="1">
      <attributes><divisions>1</divisions><key><fifths>0</fifths></key></attributes>
      <note><pitch><step>C</step><octave>4</octave></pitch><duration>1</duration><type>quarter</type></note>
      <note><pitch><step>E</step><octave>4</octave></pitch><duration>1</duration><type>quarter</type></note>
      <note><pitch><step>G</step><octave>4</octave></pitch><duration>1</duration><type>quarter</type></note>
      <note><pitch><step>C</step><octave>5</octave></pitch><duration>1</duration><type>quarter</type></note>
    </measure>
  </part>
</score-partwise>
'''
    return write_text(session_id, "score.musicxml", content)


def create_blog_post(session_id: str, mission: str, body: str | None = None) -> Path:
    content = body or f"""# {mission}

## Hook (3초)
이 멜로디, **코드 3줄**로 만들었습니다.

## 원리 (30초)
마르코프 체인 + 유클리드 리듬으로 Lo-fi 힙합을 생성합니다.
- seed=42로 재현 가능
- music21 파이프라인으로 MIDI 추출

## 데모 (20초)
`python music_generator.py` 실행 → `track.mid` 재생

## CTA
GitHub / 블로그 링크로 전체 코드 확인
"""
    return write_text(session_id, "blog_post.md", content)


def create_legal_report(session_id: str, mission: str, body: str | None = None) -> Path:
    content = body or f"""# Legal Audit Report

Mission: {mission}

## Result: PASS

- Algorithm-based generation (Markov, Euclidean rhythm)
- No existing song melody/harmony copied
- Commercial distribution: allowed

Risk Level: **LOW**
"""
    return write_text(session_id, "legal_report.md", content)
