"""Generated by Music Dev — 2026-05-24T04:05:22.347520+00:00"""
# Mission: 마르코프 체인 Ambient 곡 생성해

from music21 import stream, note, tempo, key

def generate(seed: int = 42) -> stream.Stream:
    s = stream.Stream()
    s.append(tempo.MetronomeMark(number=82))
    s.append(key.Key("C"))

    melody = ["C4", "E4", "G4", "A4", "G4", "E4", "C4", "D4"]
    for pitch in melody:
        s.append(note.Note(pitch, quarterLength=1.0))

    s.write("midi", fp="output/lofi_c_major.mid")
    return s

if __name__ == "__main__":
    generate()
